name: Docker Image CI

on:
  push:
    branches: ['main']
    paths:
      - "apps/awaken-overlay/**/*"
      - "packages/**/*"
      - ".github/workflows/**/*"
      - "pnpm-*.yaml"
      - "package.json"
      - "turbo.json"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/awaken-overlay

jobs:
  awaken-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -f apps/awaken-overlay/Dockerfile --push .
